title: "Edulabs"
description: "Documentation et plus"
remote_theme: just-the-docs/just-the-docs
url: "https://edulabs.fr"
baseurl: ""  # important si le site est à la racine du domaine
permalink: pretty

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap

search_enabled: true
enable_copy_code_button: true
heading_anchors: true

aux_links:
  "Edulabs sur GitHub": https://github.com/callmevrm/edulabs

gh_edit_link: false
gh_edit_link_text: "Modifier cette page sur GitHub"
gh_edit_repository: "https://github.com/callmevrm/edulabs"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

color_scheme: light

footer_content: '© 2025 Edulabs. Distribué sous https://github.com/callmevrm/edulabs/blob/main/LICENSEMIT License</a>.'
footer_content_license: ""
